### ISSUE TITLE
Write test cases for the game

### ISSUE THREAD

**Issue by bymayanksingh** [code-monk08/connect4#10]
you can use [unittest](https://docs.python.org/3/library/unittest.html) framework.

**Comment by Satvinder31415** [comment]
can i take this one?

**Comment by bymayanksingh** [comment]
sure

**Comment by Satvinder31415** [comment]
@code-monk08  From what I've read, it's relatively difficult and tricky to implement unit testing for pygame functions and modules. It's not recommended in general as well since graphics and implementation keep changing. Even if we do have to write test cases for it, I'd recommend doing it after the game generalizations and main menu have been implemented to prevent rewriting of code. What do you suggest?

**Comment by Satvinder31415** [comment]
I think i've found an alternative. I'll try reading more about it and try implementing it. Will keep you updated

**Comment by bymayanksingh** [comment]
alright @Satvinder31415 :+1:
